spring:
  mvc:
   view:
    prefix: /
    suffix: .jsp
  datasource: 
   driver-class-name: com.mysql.jdbc.Driver
   url: jdbc:mysql://localhost:3306/metaparkingdatabase
   username: root
   password: sql
   
  jpa:
   hibernate:
     ddl-auto: update
     show_sql: true
   database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  
  